### PR TITLE
Umbraco's update 7.4.2

### PR DESCRIPTION
**Pull request by caio-liberali-fbiz**

### CODE REVIEW

**Comment by tgriley** [comment]
Hey, sorry for the delay. I'll try to take a look at it this week.

**Comment by anD1332** [comment]
Hi,

Sorry about the delay.

I've pulled down changes, will take a look at this over the next couple of days

**Comment by anD1332** [comment]
Hi, 

This has been merged into a new branch called umbraco 7.4.2.  I haven't published the nuget package yet but will be doing that later tonight (hopefully).

Thanks
Andy

**Comment by caio-liberali-fbiz** [comment]
Thank you!

**Comment by anD1332** [comment]
This has now been made available via nuget

**Pull request closed without merging**
